const instructions = {};

//Table creation scripts
instructions.tables = {};

instructions.tables.admins =
    `CREATE TABLE admins(
        id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR(32) UNIQUE NOT NULL,
        password VARCHAR(1024) UNIQUE NOT NULL
    );`
    ;

instructions.tables.misc =
    `CREATE TABLE misc(
        attribute VARCHAR PRIMARY KEY,
        value VARCHAR UNIQUE NOT NULL
    );`
    ;

instructions.tables.users =
    `CREATE TABLE users(
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR UNIQUE NOT NULL,
        email VARCHAR UNIQUE NOT NULL,
        phoneNo VARCHAR UNIQUE NOT NULL,
        details VARCHAR UNIQUE NOT NULL,
        review_rating smallint CHECK (review_rating > 0 AND review_rating <= 5),
        review_description text,
        recommended boolean NOT NULL
    );`;

instructions.tables.blog_categories =
    `CREATE TABLE blog_categories(
        name VARCHAR PRIMARY KEY,
        description VARCHAR NOT NULL
    );`;

instructions.tables.food_categories =
    `CREATE TABLE food_categories(
        name VARCHAR PRIMARY KEY,
        description VARCHAR NOT NULL
    );`;

instructions.tables.images =
    `CREATE TABLE images(
        id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR UNIQUE NOT NULL,
        date_uploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        date_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        data BYTEA NOT NULL
    );`;

instructions.tables.employees =
    `CREATE TABLE employees(
        id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR UNIQUE NOT NULL,
        role VARCHAR UNIQUE NOT NULL,
        details VARCHAR UNIQUE NOT NULL,
        imageid smallint REFERENCES images (id) ON DELETE RESTRICT
    );`;

instructions.tables.blogs =
    `CREATE TABLE blogs(
        id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date_uploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        date_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        title VARCHAR UNIQUE NOT NULL,
        description VARCHAR,
        story text NOT NULL,
        category VARCHAR REFERENCES blog_categories (name) ON DELETE RESTRICT,
        imageid smallint REFERENCES images (id) ON DELETE RESTRICT
        );`;

instructions.tables.foods =
    `CREATE TABLE foods(
        id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date_uploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        date_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        name VARCHAR UNIQUE NOT NULL,
        description VARCHAR,
        flavour VARCHAR,
        price integer CHECK (price > 0),
        visitors bigint CHECK ( visitors > 0 ),
        recommended boolean NOT NULL,
        category VARCHAR REFERENCES food_categories (name) ON DELETE RESTRICT,
        imageid smallint REFERENCES images (id) ON DELETE RESTRICT
    );`;

module.exports = instructions;