const instructions = {};

//Table creation scripts
instructions.tables = {};

instructions.tables.admins =
    `CREATE TABLE admins(
        id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR(32) UNIQUE NOT NULL,
        password VARCHAR(1024) UNIQUE NOT NULL
    );`
    ;

instructions.tables.misc =
    `CREATE TABLE misc(
        attribute VARCHAR PRIMARY KEY,
        value VARCHAR NOT NULL
    );`
    ;

instructions.tables.users =
    `CREATE TABLE users(
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR UNIQUE NOT NULL,
        email VARCHAR UNIQUE NOT NULL,
        phone_number VARCHAR UNIQUE NOT NULL,
        details VARCHAR NOT NULL,
        review_rating smallint CHECK (review_rating > 0 AND review_rating <= 5),
        review_description text,
        highlighted boolean NOT NULL DEFAULT false
    );`;

instructions.tables.blog_categories =
    `CREATE TABLE blog_categories(
        name VARCHAR PRIMARY KEY,
        description VARCHAR NOT NULL
    );`;

instructions.tables.food_categories =
    `CREATE TABLE food_categories(
        name VARCHAR PRIMARY KEY,
        description VARCHAR NOT NULL
    );`;

instructions.tables.employees =
    `CREATE TABLE employees(
        id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR UNIQUE NOT NULL,
        role VARCHAR NOT NULL,
        details VARCHAR NOT NULL,
        image_name VARCHAR,
        image_date_updated TIMESTAMP,
        image_data BYTEA
    );`;

instructions.tables.blogs =
    `CREATE TABLE blogs(
        id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date_uploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        date_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        title VARCHAR UNIQUE NOT NULL,
        description VARCHAR,
        story text NOT NULL,
        category VARCHAR REFERENCES blog_categories (name) ON DELETE RESTRICT,
        image_name VARCHAR,
        image_date_updated TIMESTAMP,
        image_data BYTEA
        );`;

instructions.tables.foods =
    `CREATE TABLE foods(
        id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date_uploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        date_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        name VARCHAR UNIQUE NOT NULL,
        description VARCHAR,
        flavour VARCHAR,
        price integer CHECK (price > 0),
        visitors bigint CHECK ( visitors > 0 ),
        recommended boolean NOT NULL,
        category VARCHAR REFERENCES food_categories (name) ON DELETE RESTRICT,
        image_name VARCHAR,
        image_date_updated TIMESTAMP,
        image_data BYTEA
    );`;

//Table seeders
instructions.seeders = {};

instructions.seeders.misc = [
    "INSERT INTO misc(attribute , value) VALUES ('home_banner_title_white','Nasi Goreng');",
    "INSERT INTO misc(attribute , value) VALUES ('home_banner_title_orange','Pakde Har');",
    "INSERT INTO misc(attribute , value) VALUES ('home_banner_subtitle','Bukan sekadar pengganjal lapar. Nikmati porsi brutal\ndengan bumbu khas yang otentik. Harga pas di\nkantong, rasa dijamin nendang!');",
    "INSERT INTO misc(attribute , value) VALUES ('home_menu_title','Menu Unggulan Kami');",
    "INSERT INTO misc(attribute , value) VALUES ('home_menu_subtitle','Cobain menu favorit yang paling laris dan bikin ketagihan,\ndijamin bakal bikin kamu pengen nambah terus!');",
    "INSERT INTO misc(attribute , value) VALUES ('home_story_title','Cerita Kami');",
    "INSERT INTO misc(attribute , value) VALUES ('home_story_description','Didirikan pada tahun 2017 oleh Pakde Har, kedai kami menghadirkan cita rasa Indonesia yang autentik melalui hidangan andalan kami - Nasi Goreng. Berawal dari warung kecil di rumah, kini telah berkembang menjadi tempat kuliner favorit banyak orang');",
    "INSERT INTO misc(attribute , value) VALUES ('home_blog_title','Berita Harian Kami');",
    "INSERT INTO misc(attribute , value) VALUES ('home_blog_subtitle','Ikuti berbagai berita dan perkembangan terbaru dari Pakde Har');",

    "INSERT INTO misc(attribute , value) VALUES ('menu_banner_title_white','Menu');",
    "INSERT INTO misc(attribute , value) VALUES ('menu_banner_title_orange','Kami');",
    "INSERT INTO misc(attribute , value) VALUES ('menu_banner_subtitle','Temukan berbagai nasi goreng lezat yang disajikan\ndengan cinta dan rasa');",
    "INSERT INTO misc(attribute , value) VALUES ('menu_menu_title','Menu Unggulan Kami');",
    "INSERT INTO misc(attribute , value) VALUES ('menu_menu_subtitle','');",

    "INSERT INTO misc(attribute , value) VALUES ('about_banner_title_white','Cerita di Balik\nNasi Goreng');",
    "INSERT INTO misc(attribute , value) VALUES ('about_banner_title_orange','Pakde Har');",
    "INSERT INTO misc(attribute , value) VALUES ('about_banner_subtitle','Dari wajan sederhana di pinggir jalan Untar, Pakde\nHar menghadirkan cita rasa nasi goreng yang penuh\nkenangan dan kehangatan.');",
    "INSERT INTO misc(attribute , value) VALUES ('about_story_title','Dari Awal yang Sederhana');",
    "INSERT INTO misc(attribute , value) VALUES ('about_story_description','Perjalanan Pakde Har dimulai pada tahun 2017, ketika Pakde Har mulai membuat nasi goreng khas buatannya dari dapur rumah sederhana. Berkat cita rasa bumbu khas dan harga yang ramah di kantong mahasiswa, aroma nasi goreng Pakde Har cepat menarik perhatian banyak pelanggan.\nSetahun kemudian, Pakde mulai berjualan di samping Universitas Tarumanagara tempat di mana kehangatan, tawa, dan cerita para mahasiswa selalu menemani setiap wajan yang bergoyang.\nKini, Warung Nasi Goreng Pakde Har terus berkembang. Dengan tempat yang telah direnovasi, kami tetap berkomitmen menyajikan rasa autentik dan suasana akrab yang telah menjadi ciri khas kami sejak awal.');",
    "INSERT INTO misc(attribute , value) VALUES ('about_team_title','Kenali Tim Kami');",
    "INSERT INTO misc(attribute , value) VALUES ('about_team_subtitle','Orang dibalik Nasi Goreng Pakde Har');",

    "INSERT INTO misc(attribute , value) VALUES ('contact_banner_title_white','Hubungi Kami');",
    "INSERT INTO misc(attribute , value) VALUES ('contact_banner_title_orange','');",
    "INSERT INTO misc(attribute , value) VALUES ('contact_banner_subtitle','Punya pertanyaan atau saran? Kirim pesan ke kami dan\nkami siap melayani dengan sepenuh hati');",

    "INSERT INTO misc(attribute , value) VALUES ('contacts_addresses','Nasi Goreng Pakde Har\\Sebelah Alfa-X S.Parman\nJl. Taman S. Parman, RT.7/RW.8, Grogol, Kec. Grogol Petamburan, Kota Jakarta Barat, DKI Jakarta 11440&&Nasi Goreng Pakde Har\\Sebelah Alfa-X S.Parman\nJl. Taman S. Parman, RT.7/RW.8, Grogol, Kec. Grogol Petamburan, Kota Jakarta Barat, DKI Jakarta 11440');",
    "INSERT INTO misc(attribute , value) VALUES ('contacts_schedules','mon\\07:00-22:00&&tue\\07:00-22:00&&wed\\07:00-22:00&&thu\\07:00-22:00&&fri\\07:00-22:00&&sat\\CLOSED&&sun\\CLOSED');",
    "INSERT INTO misc(attribute , value) VALUES ('contacts_phone_numbers','08123456789');",
    "INSERT INTO misc(attribute , value) VALUES ('contacts_emails','pakdehar@gmail.com');",
];


instructions.seeders.employees = [
    "INSERT INTO employees (name , role, details) VALUES ('Pakde Har' , 'Owner' , 'Some description')",
    "INSERT INTO employees (name , role, details) VALUES ('Employee No 2' , 'employee' , 'Some description')",
    "INSERT INTO employees (name , role, details) VALUES ('Employee No 3' , 'employee' , 'Some description')",
];

instructions.seeders.blog_categories = [
    "INSERT INTO blog_categories (name , description) VALUES ('good news' , 'good news description')",
    "INSERT INTO blog_categories (name , description) VALUES ('bad news' , 'bad news description')",
    "INSERT INTO blog_categories (name , description) VALUES ('woof news' , 'woof news description')",
];

instructions.seeders.food_categories = [
    "INSERT INTO food_categories (name , description) VALUES ('food food' , 'food food description')",
    "INSERT INTO food_categories (name , description) VALUES ('bad food' , 'bad food description')",
    "INSERT INTO food_categories (name , description) VALUES ('woof food' , 'woof food description')",
];

instructions.seeders.blogs = [
    "INSERT INTO blogs (title , story, category) VALUES ('STORY 1' , 'Description 1' , 'good news')",
    "INSERT INTO blogs (title , story) VALUES ('STORY 2' , 'Description 2')",
    "INSERT INTO blogs (title , story , category) VALUES ('STORY 3' , 'Description 3' , 'bad news')",
    "INSERT INTO blogs (title , story) VALUES ('STORY 4' , 'Description 4')",
    "INSERT INTO blogs (title , story) VALUES ('STORY 5' , 'Description 5')",
    "INSERT INTO blogs (title , story) VALUES ('STORY 6' , 'Description 6')",
    "INSERT INTO blogs (title , story , category) VALUES ('STORY 7' , 'Description 7' , 'woof news')",
    "INSERT INTO blogs (title , story) VALUES ('STORY 8' , 'Description 8')",
    "INSERT INTO blogs (title , story) VALUES ('STORY 9' , 'Description 9')",
    "INSERT INTO blogs (title , story) VALUES ('STORY 10' , 'Description 10')",
];

/*
    DELIMITERS
    \n == next line delimiter
    \\ == attribute-value delimiter
    && == array delimiter
 */

module.exports = instructions;